-- MySQL initialization scripts are executed before tables are created by SQLAlchemy.
-- All seed data has been moved to app/db/seed.py and is executed after table creation.
-- This file is intentionally left empty.
